# Generated by Django 5.1.2 on 2024-10-23 19:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="author",
            field=models.CharField(default="", max_length=15),
        ),
        migrations.AddField(
            model_name="book",
            name="created_at",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="book",
            name="like_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="book",
            name="written_date",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
